default_context:
  project_name: 'Datengenerator'
  project_slug: 'datengenerator'
  domain_main: 'datengenerator.com'
  backend_cors_origins: 'http://localhost'
  docker_swarm_stack_name_main: 'datengenerator-com'
  traefik_constraint_tag: 'datengenerator.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*]
  _template: ./
