version: '3'
services:
  backend:
    volumes:
      - ./backend/app:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=5000'
    command: flask run --host=0.0.0.0 --port=5000

##########################################################################################

  frontend:
    build: 
        context: ./frontend
    ports:
        - "80:80"
    volumes:
        - ./frontend:/user/src/app
    depends_on:
        - backend

##########################################################################################

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS-LOGIN=yes
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Random-Signal:1:1,Sinus-Signal:1:1,Cosinus-Signal:1:1,Emphasized-Signal:1:1,Spiked-Signal:1:1"
