version: "2"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    network_mode: host
    volumes:
      - /config:/config
      - /data:/data
      - /log:/log
    ports:
      - "1883:1883"
      - "9001:9001"