/// <reference types="cypress" />

describe("Visit Data Generator Page and start all types of signals", () => {
    it("Create Random Signal", () => {
        cy.visit("/")
        cy.get("#name").type("rand").should('have.value', "rand")
        cy.get("#lowerBoundary").type(2).should('have.value', 2)
        cy.get("#upperBoundary").type(4).should('have.value', 4)
        cy.get("#transmissionFrequency").type(6).should('have.value', 6)
        cy.get("[data-testid='ArrowDropDownIcon']").click()
        cy.contains("#mui-1-option-2", 'websocket').click()
        cy.contains("button", "CREATE").click()
        cy.get('.css-1kav7zp-MuiPaper-root > .MuiPaper-root').should("contain", "rand")
    })

    it("Create Sinus Signal", () => {
        cy.visit("/")
        cy.get("button").contains("SINUS SIGNAL").click()
        cy.get('#outlined-basic').type("sin").should('have.value', "sin")
        cy.get(':nth-child(4) > .MuiOutlinedInput-root > #formatted-numberformat-input').type(2)
        .should('have.value', 2)
        cy.get(':nth-child(6) > .MuiOutlinedInput-root > #formatted-numberformat-input').type(4)
        .should('have.value', 4)
        cy.get(':nth-child(8) > .MuiOutlinedInput-root > #formatted-numberformat-input').type(6)
        .should('have.value', 6)
        cy.get("[data-testid='ArrowDropDownIcon']").click()
        cy.contains("#mui-2-option-2", 'websocket').click()
        cy.contains("button", "CREATE").click()
        cy.get('.css-1kav7zp-MuiPaper-root > .MuiPaper-root').should("contain", "sin")
    })

    it("Create Cosinus Signal", () => {
        cy.visit("/")
        cy.get("button").contains("COSINUS SIGNAL").click()
        cy.get('#outlined-basic').type("cos").should("have.value", "cos")
        cy.get(':nth-child(4) > .MuiOutlinedInput-root > #formatted-numberformat-input').type(2)
        .should('have.value', 2)
        cy.get(':nth-child(6) > .MuiOutlinedInput-root > #formatted-numberformat-input').type(4)
        .should('have.value', 4)
        cy.get(':nth-child(8) > .MuiOutlinedInput-root > #formatted-numberformat-input').type(6)
        .should('have.value', 6)
        cy.get("[data-testid='ArrowDropDownIcon']").click()
        cy.contains("#mui-2-option-2", 'websocket').click()
        cy.contains("button", "CREATE").click()
        cy.get('.css-1kav7zp-MuiPaper-root > .MuiPaper-root').should("contain", "cos")
    })

    it("Create Spiked Signal", () => {
        cy.visit("/")
        cy.get("button").contains("SPIKED SIGNAL").click()
        cy.get('#outlined-basic').type("spi")
        cy.get(':nth-child(4) > .MuiOutlinedInput-root > #formatted-numberformat-input').type(2)
        .should('have.value', 2)
        cy.get(':nth-child(6) > .MuiOutlinedInput-root > #formatted-numberformat-input').type(4)
        .should('have.value', 4)
        cy.get(':nth-child(8) > .MuiOutlinedInput-root > #formatted-numberformat-input').type(6)
        .should('have.value', 6)
        cy.get(':nth-child(10) > .MuiOutlinedInput-root > #formatted-numberformat-input').type(8)
        .should('have.value', 8)
        cy.get(':nth-child(12) > .MuiOutlinedInput-root > #formatted-numberformat-input').type(10)
        .should('have.value', 10)
        cy.get("[data-testid='ArrowDropDownIcon']").click()
        cy.contains("#mui-2-option-2", 'websocket').click()
        cy.contains("button", "CREATE").click()
       cy.get('.css-1kav7zp-MuiPaper-root > .MuiPaper-root').should("contain", "spi")
    })

    it("Create Normally Distributed Signal", () => {
        cy.visit("/")
        cy.get("button").contains("NORM. DIST. SIGNAL").click()
        cy.get('#outlined-basic').type("norm")
        cy.get(':nth-child(4) > .MuiOutlinedInput-root > #formatted-numberformat-input').type(2)
        .should('have.value', 2)
        cy.get(':nth-child(6) > .MuiOutlinedInput-root > #formatted-numberformat-input').type(4)
        .should('have.value', 4)
        cy.get(':nth-child(8) > .MuiOutlinedInput-root > #formatted-numberformat-input').type(6)
        .should('have.value', 6)
        cy.get("[data-testid='ArrowDropDownIcon']").click()
        cy.contains("#mui-2-option-2", 'websocket').click()
        cy.contains("button", "CREATE").click()
        cy.get('.css-1kav7zp-MuiPaper-root > .MuiPaper-root').should("contain", "norm")
    })

    it("Start all streams", () => {
        cy.wait(2000)
        cy.get('[data-testid="PlayCircleFilledWhiteRoundedIcon"]').click()
        cy.wait(2000)
        cy.get('[data-testid="PlayCircleFilledWhiteRoundedIcon"]').click()
        cy.wait(2000)
        cy.get('.css-ne2ks3-MuiGrid-root > .MuiTypography-root').should("contain", "5 / 5")
    })
    
  })